(()=>{
  const ID='ari-dashboard-menu-hof404',CONTEXT_KEY='ari-context-system',THEME_KEY='ari-theme',REFRESH_ID='ari-global-refresh';
  const VALID=new Set(['dark','sepia','red-night']);
  const ROUTES=[
    {icon:'◆',title:'HERMES',detail:'Clínicas · Pipeline · Citas',href:'/ari/hermes/'},
    {icon:'⌁',title:'TRADING',detail:'Mercado · Gráficos · Operaciones',href:'/ari/trading/'},
    {icon:'♫',title:'MÚSICA',detail:'DAW · Creación · Producción',href:'/ari/music/'},
    {icon:'🛒',title:'LISTA DE LA COMPRA',detail:'Pendientes del súper',href:'/ari/shopping/'}
  ];
  function normalizeTheme(v){if(v==='light'||v==='auto'||!v)return'sepia';return VALID.has(v)?v:'sepia'}
  function theme(){const t=normalizeTheme(localStorage.getItem(THEME_KEY));if(localStorage.getItem(THEME_KEY)!==t)localStorage.setItem(THEME_KEY,t);return t}
  function ensureGlobalStyle(){
    let s=document.getElementById('ari-global-ui-style');if(!s){s=document.createElement('style');s.id='ari-global-ui-style';document.head.appendChild(s)}
    s.textContent=`
      html[data-theme="sepia"]{color-scheme:light;--bg:#f4eadb!important;--panel:#f7efe3!important;--panel2:#eadfce!important;--chrome:#f4eadb!important;--chrome2:#eadfce!important;--grid:#e2d4c1!important;--grid-strong:#cbb99f!important;--line:#d3c2aa!important;--border:#d3c2aa!important;--text:#2d261f!important;--muted:#7f705e!important;--muted2:#6f6252!important;--gold:#a9792d!important;--accent:#a9792d!important;--accent-soft:#ead9b8!important;--bottom:rgba(244,234,219,.97)!important;--header:rgba(244,234,219,.95)!important;--phase-a:#e2d6c6!important;--phase-b:#d4c5b2!important;--phase-border:#c9b99f!important;--task-bg:#d8c09a!important;--task-border:#b9965c!important;--task-accent:#8d6424!important;--ticket:rgba(247,239,227,.98)!important;--chart-sepia:#eee6d2!important;--chart-grid:rgba(76,67,52,.10)!important}
      html[data-theme="sepia"],html[data-theme="sepia"] body,html[data-theme="sepia"] .app,html[data-theme="sepia"] .shell{background-color:#f4eadb!important}
      html[data-theme="dark"]{color-scheme:dark;--bg:#050505!important;--panel:#101010!important;--panel2:#171717!important;--chrome:#0b0b0b!important;--chrome2:#151515!important;--grid:#1b1b1b!important;--grid-strong:#303030!important;--line:#2b2b2b!important;--border:#303030!important;--text:#f2f2f2!important;--muted:#9b9b9b!important;--muted2:#b0b0b0!important;--gold:#d8a84b!important;--accent:#c9a45b!important;--accent-soft:#292929!important;--bottom:rgba(5,5,5,.97)!important;--header:rgba(5,5,5,.94)!important;--phase-a:#161616!important;--phase-b:#242424!important;--phase-border:#353535!important;--task-bg:#252525!important;--task-border:#444!important;--task-accent:#d2b06b!important;--ticket:rgba(20,20,20,.98)!important;--chart-sepia:#090909!important;--chart-grid:rgba(255,255,255,.08)!important}
      html[data-theme="red-night"]{color-scheme:dark;--bg:#090000!important;--panel:#120202!important;--panel2:#1a0303!important;--chrome:#0c0000!important;--chrome2:#160202!important;--grid:#240707!important;--grid-strong:#401010!important;--line:#3a0d0d!important;--border:#461010!important;--text:#efb1a8!important;--muted:#ad625b!important;--muted2:#c77870!important;--gold:#d65a4f!important;--accent:#d65a4f!important;--accent-soft:#3a0b0b!important;--bottom:rgba(9,0,0,.98)!important;--header:rgba(9,0,0,.97)!important;--phase-a:#160202!important;--phase-b:#230404!important;--phase-border:#481010!important;--task-bg:#3a0909!important;--task-border:#6f1919!important;--task-accent:#d65a4f!important;--good:#d77a70!important;--warn:#c66359!important;--bad:#ff7468!important;--danger:#ff6b61!important;--ticket:rgba(22,2,2,.98)!important;--chart-sepia:#090000!important;--chart-grid:rgba(205,80,70,.12)!important}
      html[data-theme="red-night"] img:not(.logo),html[data-theme="red-night"] video{filter:sepia(1) saturate(3.8) hue-rotate(315deg) brightness(.58) contrast(1.15)}
      html[data-theme="red-night"] #tv iframe,html[data-theme="red-night"] .chart iframe,html[data-theme="red-night"] canvas{filter:sepia(1) saturate(4.2) hue-rotate(315deg) brightness(.52) contrast(1.25)}
      html[data-theme="dark"] #tv iframe{filter:invert(.9) hue-rotate(180deg) saturate(.45) brightness(.72) contrast(1.08)}
      #${REFRESH_ID}{appearance:none;border:0;background:transparent;font:inherit;cursor:pointer}#${REFRESH_ID}[disabled]{opacity:.55;cursor:default}
    `;
  }
  function applyGlobalTheme(next){const t=normalizeTheme(next||localStorage.getItem(THEME_KEY));if(localStorage.getItem(THEME_KEY)!==t)localStorage.setItem(THEME_KEY,t);document.documentElement.dataset.theme=t;if(t==='sepia')document.documentElement.style.backgroundColor='#f4eadb';else document.documentElement.style.removeProperty('background-color');const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=t==='dark'?'#050505':t==='red-night'?'#090000':'#f4eadb';document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===t));window.dispatchEvent(new CustomEvent('ari-theme-change',{detail:{theme:t}}));return t}
  function setTheme(t){const n=normalizeTheme(t);localStorage.setItem(THEME_KEY,n);applyGlobalTheme(n)}
  function ensureThemeSelector(){const view=document.querySelector('.view[data-view="apariencia"]');if(!view)return;const row=view.querySelector('.theme-row');if(!row)return;row.innerHTML='<button class="theme-option" data-theme-choice="dark">🌙 OSCURO</button><button class="theme-option" data-theme-choice="sepia">☀️ SEPIA</button><button class="theme-option" data-theme-choice="red-night">◉ ROJO NOCHE</button>';row.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=()=>setTheme(b.dataset.themeChoice));const menuCopy=document.querySelector('#openAppearance .menu-copy span');if(menuCopy)menuCopy.textContent='Oscuro, sepia o rojo noche';applyGlobalTheme()}
  async function hardRefresh(btn){if(btn?.disabled)return;if(btn){btn.disabled=true;const b=btn.querySelector('b');if(b)b.textContent='…'}try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs)await r.update()}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('ari-')).map(k=>caches.delete(k)))}const u=new URL(location.href);u.searchParams.set('refresh',Date.now());location.replace(u.toString())}catch(e){if(btn){btn.disabled=false;const b=btn.querySelector('b');if(b)b.textContent='↻'}}}
  function layoutBottom(nav){const visible=[...nav.children].filter(x=>!x.hidden&&getComputedStyle(x).display!=='none').length;if(visible)nav.style.gridTemplateColumns=`repeat(${visible},minmax(0,1fr))`}
  function ensureRefresh(){const nav=document.querySelector('nav.bottom,.bottom');if(!nav)return;let btn=document.getElementById(REFRESH_ID)||document.getElementById('refreshApp');if(!btn){btn=document.createElement('button');btn.id=REFRESH_ID;btn.className='nav';btn.type='button';btn.innerHTML='<b>↻</b>Actualizar';nav.appendChild(btn)}if(!btn.dataset.globalRefresh){btn.dataset.globalRefresh='1';btn.addEventListener('click',()=>hardRefresh(btn))}layoutBottom(nav)}
  function ensureDashboardMenu(){if(document.getElementById(ID))return;const view=document.querySelector('.view[data-view="menu"]');if(!view)return;const status=view.querySelector('#updateStatus'),section=document.createElement('section');section.id=ID;section.innerHTML=`<div class="section-title">DASHBOARDS / SISTEMAS</div><div class="menu-list">${ROUTES.map(r=>`<button class="menu-item" data-dashboard-route="${r.href}"><span class="menu-main"><span class="menu-icon">${r.icon}</span><span class="menu-copy"><strong>${r.title}</strong><span>${r.detail}</span></span></span><span class="chev">›</span></button>`).join('')}</div>`;if(status)view.insertBefore(section,status);else view.appendChild(section);section.querySelectorAll('[data-dashboard-route]').forEach(b=>b.addEventListener('click',()=>location.assign(b.dataset.dashboardRoute)))}
  function loadScript(src,key){if(document.querySelector(`script[data-ari-${key}]`))return;const s=document.createElement('script');s.src=src;s.dataset['ari'+key.replace(/(^|-)([a-z])/g,(_,a,b)=>b.toUpperCase())]='1';s.defer=true;document.head.appendChild(s)}
  function ensureMusicTools(){if(!location.pathname.startsWith('/ari/music/'))return;if(!window.ARI_HISTORY_READY)loadScript('/ari/music/undo-redo.js?v=1','undo-redo');if(!window.ARI_DAW_SPLIT_CLIP)loadScript('/ari/music/clip-tools.js?v=1','clip-tools');if(!window.ARI_SYNC_RECORDINGS)loadScript('/ari/music/recording-sync.js?v=2','recording-sync');if(!window.ARI_EXPORT_MP3)loadScript('/ari/music/project-actions.js?v=2','project-actions');if(!window.ARI_IMPORT_AUDIO_FILES)loadScript('/ari/music/drag-drop-import.js?v=1','drag-drop-import');if(!window.ARI_TRACK_VOLUME_UI)loadScript('/ari/music/track-volume-ui.js?v=2','track-volume-ui');if(!window.ARI_DUPLICATE_TRACK)loadScript('/ari/music/duplicate-track.js?v=1','duplicate-track');if(!window.ARI_VOCAL_MIX_LIGHT)loadScript('/ari/music/vocal-mix-light.js?v=1','vocal-mix-light');if(localStorage.getItem('ari-ganador-reference-session-v1')!=='1')loadScript('/ari/music/reference-session.js?v=1','reference-session')}
  function ensureTradingTools(){if(!location.pathname.startsWith('/ari/trading/'))return;loadScript('/ari/trading/candle-countdown-v2.js?v=2','trading-candle-countdown')}
  function syncContext(){const el=document.getElementById('contextMusic'),nav=document.getElementById('bottomNav');if(!el||!nav){ensureRefresh();return}const ctx=localStorage.getItem(CONTEXT_KEY);if(ctx==='music'){el.href='/ari/music/?resume=1';el.innerHTML='<b>♫</b>Música';el.hidden=false;nav.classList.add('has-context')}else if(ctx==='trading'){el.href='/ari/trading/?resume=1';el.innerHTML='<b>⌁</b>Trading';el.hidden=false;nav.classList.add('has-context')}else if(ctx==='hermes'){el.href='/ari/hermes/';el.innerHTML='<b>◆</b>Hermes';el.hidden=false;nav.classList.add('has-context')}else{el.hidden=true;nav.classList.remove('has-context')}ensureRefresh();layoutBottom(nav)}
  function ensure(){ensureGlobalStyle();applyGlobalTheme();ensureThemeSelector();ensureDashboardMenu();syncContext();ensureRefresh();ensureMusicTools();ensureTradingTools()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure,{once:true});else ensure();
  addEventListener('pageshow',ensure);addEventListener('storage',e=>{if(e.key===CONTEXT_KEY)syncContext();if(e.key===THEME_KEY)applyGlobalTheme(e.newValue)});
  window.ARI_THEME={key:THEME_KEY,get:theme,set:setTheme,apply:applyGlobalTheme,modes:['dark','sepia','red-night']};window.ARI_ENSURE_DASHBOARDS=ensure;window.ARI_HARD_REFRESH=hardRefresh;
})();