const API='/api/ari-courses?path=';let catalog,currentLesson,lastSave=0,resumeApplied=false;
const $=id=>document.getElementById(id);function fmt(v){let s=Math.max(0,Math.round(+v||0)),h=Math.floor(s/3600),m=Math.floor(s%3600/60),q=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(q).padStart(2,'0')}`:`${m}:${String(q).padStart(2,'0')}`}
function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}function theme(){let c=localStorage.getItem('ari-theme')||'auto',r=c==='auto'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):c;document.documentElement.dataset.theme=r;$('themeColor').content=r==='dark'?'#050505':'#f5f1e8'}theme();
async function api(path,opts={}){const r=await fetch(API+encodeURIComponent(path),{cache:'no-store',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});let x={};try{x=await r.json()}catch{}if(!r.ok)throw Error(x.error||`HTTP ${r.status}`);return x}
function view(name){$('libraryView').hidden=name!=='library';$('courseView').hidden=name!=='course';$('lessonView').hidden=name!=='lesson';scrollTo(0,0)}
function renderCatalog(q=''){q=q.trim().toLowerCase();$('areas').innerHTML='';for(const a of catalog.areas){const cs=a.courses.filter(c=>!q||`${c.title} ${c.author_school} ${c.tags}`.toLowerCase().includes(q));if(q&&!cs.length)continue;const sec=document.createElement('section');sec.className='area';sec.innerHTML=`<h3>${esc(a.name)}</h3><div class="cards">${cs.map(c=>`<button class="course" data-course="${esc(c.id)}"><span><strong>${esc(c.title)}</strong><small>${esc(c.author_school)} · ${esc(c.status)}</small></span><b>›</b></button>`).join('')}</div>`;$('areas').appendChild(sec)}document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>openCourse(b.dataset.course));$('catalogStatus').textContent=`${catalog.areas.length} áreas · ${catalog.areas.reduce((n,a)=>n+a.courses.length,0)} cursos`;$('catalogStatus').className='status ok'}
function renderQA(){const q=catalog.qa_lesson,p=q.progress||{},pct=+p.progress_pct||0;$('qaCard').innerHTML=`<button class="qa-card" id="openQa"><span><strong>${esc(q.title)}</strong><small>${fmt(q.duration_seconds)} · ${esc(q.license_name)} · ${pct.toFixed(1)}%</small></span><b>›</b></button>`;$('openQa').onclick=()=>openLesson(q.id);if(+p.position_seconds>2&&!p.completed){$('continuePanel').hidden=false;$('continueTitle').textContent=q.title;$('continueMeta').textContent=`Reanudar en ${fmt(p.position_seconds)} · ${pct.toFixed(1)}%`;$('continueBtn').onclick=()=>openLesson(q.id)}else $('continuePanel').hidden=true}
async function loadCatalog(){try{catalog=await api('catalog');renderCatalog($('searchInput').value);renderQA()}catch(e){$('catalogStatus').textContent='Biblioteca no disponible: '+e.message;$('catalogStatus').className='status error'}}
async function openCourse(id){try{const c=(await api('course/'+id)).course;$('courseTitle').textContent=c.title;$('courseAuthor').textContent=c.author_school;$('courseLessons').innerHTML=c.lessons?.length?c.lessons.map(l=>`<button class="qa-card" data-lesson="${esc(l.id)}"><span><strong>${esc(l.title)}</strong><small>${fmt(l.duration_seconds)}</small></span><b>›</b></button>`).join(''):'<div class="empty">Curso catalogado. Pendiente de ingesta de lecciones autorizadas.</div>';document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));view('course')}catch(e){$('catalogStatus').textContent=e.message}}
async function openLesson(id){try{currentLesson=(await api('lesson/'+id)).lesson;resumeApplied=false;$('lessonTitle').textContent=currentLesson.title;$('lessonMeta').textContent=`${currentLesson.course_title} · ${fmt(currentLesson.duration_seconds)} · ${currentLesson.media_format}`;$('license').innerHTML=`Fuente: <a target="_blank" rel="noopener" href="${esc(currentLesson.source_original)}">Wikimedia Commons</a><br>Licencia: <a target="_blank" rel="noopener" href="${esc(currentLesson.license_url)}">${esc(currentLesson.license_name)}</a><br>Atribución: ${esc(currentLesson.attribution)}`;$('notes').value=currentLesson.progress?.notes||'';$('completeBtn').textContent=currentLesson.progress?.completed?'✓ Completado':'Marcar completado';progressUI(currentLesson.progress?.position_seconds||0,currentLesson.progress?.progress_pct||0,currentLesson.progress?.completed);view('lesson');$('saveStatus').textContent='Solicitando acceso al storage…';const m=await api('media/'+id);$('video').src=m.url;$('video').load();$('saveStatus').textContent='Storage listo · URL firmada temporal'}catch(e){$('saveStatus').textContent='No se pudo abrir: '+e.message;$('saveStatus').className='status error'}}
function progressUI(pos,pct,done){const d=currentLesson?.duration_seconds||$('video').duration||0,p=done?100:Math.max(0,Math.min(100,(+pct||(d?pos/d*100:0))));$('progressBar').style.width=p+'%';$('progressText').textContent=(done?'100':p.toFixed(1))+'%'+(done?' · completado':'');$('positionText').textContent=`${fmt(pos)} / ${fmt(d)}`}
async function save(force=false,done=null){if(!currentLesson)return;let t=Date.now();if(!force&&t-lastSave<10000)return;lastSave=t;let completed=done===null?!!currentLesson.progress?.completed:!!done,payload={position_seconds:+$('video').currentTime||+currentLesson.progress?.position_seconds||0,completed,notes:$('notes').value};try{const p=(await api('progress/'+currentLesson.id,{method:'PUT',body:JSON.stringify(payload)})).progress;currentLesson.progress=p;progressUI(p.position_seconds,p.progress_pct,p.completed);$('saveStatus').textContent='Progreso guardado · '+new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});renderQA()}catch(e){$('saveStatus').textContent='Error guardando progreso'}}
const v=$('video');v.addEventListener('loadedmetadata',()=>{let p=+currentLesson?.progress?.position_seconds||0;if(!resumeApplied&&p>2&&p<v.duration-2){v.currentTime=p;resumeApplied=true}progressUI(v.currentTime,currentLesson?.progress?.progress_pct||0,currentLesson?.progress?.completed)});v.addEventListener('timeupdate',()=>{let d=currentLesson?.duration_seconds||v.duration||0;progressUI(v.currentTime,d?v.currentTime/d*100:0,currentLesson?.progress?.completed);save(false)});v.addEventListener('pause',()=>save(true));v.addEventListener('ended',()=>save(true,true));$('speed').onchange=()=>v.playbackRate=+$('speed').value;$('fullscreenBtn').onclick=()=>v.requestFullscreen?.()||v.webkitEnterFullscreen?.();$('completeBtn').onclick=async()=>{await save(true,true);$('completeBtn').textContent='✓ Completado'};$('notes').onchange=()=>save(true);addEventListener('pagehide',()=>save(true));$('backCourse').onclick=()=>view('library');$('backLesson').onclick=async()=>{await save(true);view('library');await loadCatalog()};$('searchInput').oninput=()=>catalog&&renderCatalog($('searchInput').value);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/ari/sw.js').catch(()=>{}));loadCatalog();
