(()=>{
  const PROJECT_KEY='ari-daw-project-v0',DB_NAME='ari-daw-audio',STORE='blobs',BUTTON_ID='ari-split-clip';
  const uid=()=>crypto.randomUUID?.()||('id_'+Date.now()+'_'+Math.random().toString(36).slice(2));
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  function toast(msg){const t=document.getElementById('toast');if(t){t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1900)}else console.log('[A.R.I. DAW]',msg)}
  function readProject(){try{return JSON.parse(localStorage.getItem(PROJECT_KEY)||'null')}catch{return null}}
  function writeProject(p){p.updatedAt=new Date().toISOString();localStorage.setItem(PROJECT_KEY,JSON.stringify(p))}
  function selectedClipId(){return document.querySelector('.clip.selected')?.dataset.clip||null}
  function findClip(p,id){for(const track of p?.tracks||[]){const clip=(track.clips||[]).find(c=>c.id===id);if(clip)return{track,clip}}return null}
  function cursorBeat(){const ph=document.getElementById('playhead');if(!ph)return 0;const cs=getComputedStyle(document.documentElement),header=parseFloat(cs.getPropertyValue('--headerw'))||196,bar=parseFloat(cs.getPropertyValue('--barw'))||104;const x=parseFloat(ph.style.left)||ph.offsetLeft||header;return Math.max(0,(x-header)/bar*4)}
  async function openDb(){return await new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function getBlob(id){const d=await openDb();return await new Promise((res,rej)=>{const tx=d.transaction(STORE);const r=tx.objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function putBlob(id,blob){const d=await openDb();return await new Promise((res,rej)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(blob,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
  function writeStr(v,o,s){for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))}
  function wavSlice(buffer,startSec,endSec){const sr=buffer.sampleRate,ch=Math.max(1,Math.min(2,buffer.numberOfChannels)),a=clamp(Math.floor(startSec*sr),0,buffer.length),b=clamp(Math.floor(endSec*sr),a,buffer.length),frames=Math.max(1,b-a),bytes=frames*ch*2,out=new ArrayBuffer(44+bytes),v=new DataView(out);writeStr(v,0,'RIFF');v.setUint32(4,36+bytes,true);writeStr(v,8,'WAVE');writeStr(v,12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,sr,true);v.setUint32(28,sr*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);writeStr(v,36,'data');v.setUint32(40,bytes,true);let o=44;const data=[];for(let c=0;c<ch;c++)data.push(buffer.getChannelData(c));for(let i=a;i<b;i++){for(let c=0;c<ch;c++){let x=Math.max(-1,Math.min(1,data[c][i]||0));v.setInt16(o,x<0?x*0x8000:x*0x7fff,true);o+=2}}return new Blob([out],{type:'audio/wav'})}
  function splitMidi(track,clip,cutAbs){const cut=cutAbs-clip.start,end=clip.start+clip.length,right=typeof structuredClone==='function'?structuredClone(clip):JSON.parse(JSON.stringify(clip)),src=[...(clip.notes||[])],left=[],rn=[];for(const n of src){const ns=n.at,ne=n.at+n.length;if(ns<cut){const ll=Math.min(n.length,cut-ns);if(ll>.0001)left.push({...n,id:uid(),length:ll})}if(ne>cut){const rs=Math.max(ns,cut),rl=ne-rs;if(rl>.0001)rn.push({...n,id:uid(),at:rs-cut,length:rl})}}clip.length=cut;clip.notes=left;clip.name=(clip.name||'MIDI').replace(/ · [AB]$/,'')+' · A';right.id=uid();right.start=cutAbs;right.length=end-cutAbs;right.notes=rn;right.name=(clip.name||'MIDI').replace(/ · A$/,'')+' · B';track.clips.push(right);return right.id}
  async function splitAudio(project,track,clip,cutAbs){if(!clip.blobId)throw new Error('clip sin audio');const blob=await getBlob(clip.blobId);if(!blob)throw new Error('audio no encontrado');const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw new Error('Web Audio no disponible');const ac=new AC();let buf;try{buf=await ac.decodeAudioData(await blob.arrayBuffer())}finally{ac.close?.().catch?.(()=>{})}const bpm=Number(project.bpm)||72,spb=60/bpm,cutBeats=cutAbs-clip.start,endAbs=clip.start+clip.length,clipEndSec=Math.min(buf.duration,clip.length*spb),cutSec=clamp(cutBeats*spb,.001,Math.max(.001,clipEndSec-.001));const leftBlob=wavSlice(buf,0,cutSec),rightBlob=wavSlice(buf,cutSec,clipEndSec),leftId=uid(),rightId=uid();await Promise.all([putBlob(leftId,leftBlob),putBlob(rightId,rightBlob)]);const right=typeof structuredClone==='function'?structuredClone(clip):JSON.parse(JSON.stringify(clip));const base=(clip.name||'AUDIO').replace(/ · [AB]$/,'');clip.length=cutBeats;clip.blobId=leftId;clip.name=base+' · A';right.id=uid();right.start=cutAbs;right.length=endAbs-cutAbs;right.blobId=rightId;right.name=base+' · B';track.clips.push(right);return right.id}
  async function splitSelected(){const p=readProject(),id=selectedClipId();if(!p||!id){toast('Selecciona un clip');return}const f=findClip(p,id);if(!f){toast('Clip no encontrado');return}const at=cursorBeat(),end=f.clip.start+f.clip.length;if(!(at>f.clip.start+.01&&at<end-.01)){toast('Pon el cursor dentro del clip');return}try{let newId;if(f.clip.type==='audio'){toast('Dividiendo audio…');newId=await splitAudio(p,f.track,f.clip,at)}else newId=splitMidi(f.track,f.clip,at);writeProject(p);sessionStorage.setItem('ari-daw-select-clip',newId);location.reload()}catch(e){console.error(e);toast('No pude dividir este clip')}
  function deleteSelected(){const id=selectedClipId();if(!id)return;const b=document.getElementById('deleteClip');if(b){b.click();return}const p=readProject(),f=findClip(p,id);if(!f)return;f.track.clips=f.track.clips.filter(c=>c.id!==id);writeProject(p);location.reload()}
  function duplicateSelected(){const id=selectedClipId();if(!id)return;const b=document.getElementById('dupClip');if(b){b.click();return}const p=readProject(),f=findClip(p,id);if(!f)return;const c=f.clip,copy=typeof structuredClone==='function'?structuredClone(c):JSON.parse(JSON.stringify(c));copy.id=uid();copy.name=(c.name||'CLIP')+' copia';copy.start=Math.min(c.start+c.length,p.bars*4-c.length);if(copy.notes)copy.notes=copy.notes.map(n=>({...n,id:uid()}));f.track.clips.push(copy);writeProject(p);location.reload()}
  function addControls(){const editor=document.querySelector('#inspectorBody .clip-editor'),id=selectedClipId();if(!editor||!id)return;if(!document.getElementById(BUTTON_ID)){const b=document.createElement('button');b.id=BUTTON_ID;b.className='smallbtn';b.textContent='DIVIDIR · ⌘E';b.title='Divide el clip exactamente en el cursor';b.onclick=splitSelected;const dup=document.getElementById('dupClip');editor.insertBefore(b,dup||null)}const del=document.getElementById('deleteClip'),dup=document.getElementById('dupClip');if(del&&!/⌫/.test(del.textContent))del.textContent='BORRAR · ⌫';if(dup&&!/⌘D/.test(dup.textContent))dup.textContent='DUPLICAR · ⌘D'}
  function restoreSelection(){const id=sessionStorage.getItem('ari-daw-select-clip');if(!id)return;sessionStorage.removeItem('ari-daw-select-clip');setTimeout(()=>{const el=document.querySelector(`.clip[data-clip="${CSS.escape(id)}"]`);el?.click()},120)}
  function ensureDeleteModule(){if(window.ARI_DELETE_TRACK_CLIP_READY||document.querySelector('script[data-ari-delete-track-clip]'))return;const s=document.createElement('script');s.src='/ari/music/delete-track-clip.js?v=1';s.dataset.ariDeleteTrackClip='1';s.defer=true;document.head.appendChild(s)}
  const obs=new MutationObserver(()=>addControls());function init(){ensureDeleteModule();const body=document.getElementById('inspectorBody');if(body)obs.observe(body,{childList:true,subtree:true});addControls();restoreSelection()}
  addEventListener('keydown',e=>{const tag=e.target?.tagName;if(tag==='INPUT'||tag==='TEXTAREA'||tag==='SELECT')return;const k=e.key.toLowerCase();if((e.metaKey||e.ctrlKey)&&k==='e'&&selectedClipId()){e.preventDefault();splitSelected()}else if((e.metaKey||e.ctrlKey)&&k==='d'&&selectedClipId()){e.preventDefault();duplicateSelected()}else if((e.key==='Backspace'||e.key==='Delete')&&selectedClipId()){e.preventDefault();deleteSelected()}});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
  window.ARI_DAW_SPLIT_CLIP=splitSelected;
})();