(()=>{ if(!location.pathname.startsWith('/ari/music/'))return;
const PK='ari-daw-project-v0',MK='ari-music-browser-collapsed-v1';
const uid=()=>crypto.randomUUID?.()||('id_'+Date.now()+'_'+Math.random().toString(36).slice(2));
const read=()=>{try{return JSON.parse(localStorage.getItem(PK)||'null')}catch{return null}};
const save=p=>{p.updatedAt=new Date().toISOString();localStorage.setItem(PK,JSON.stringify(p))};
const fx=(lo,hi,th,ra,ga,rv,de=.03,dt=.14)=>[
 {id:uid(),type:'EQ',enabled:true,low:lo,high:hi},{id:uid(),type:'COMP',enabled:true,threshold:th,ratio:ra},
 {id:uid(),type:'GAIN',enabled:true,value:ga},{id:uid(),type:'REVERB',enabled:true,mix:rv},{id:uid(),type:'DELAY',enabled:true,mix:de,time:dt}];
const VOICES=[
 ['principal','VOZ PRINCIPAL','Clara, delante y natural.',1,0,[-3,1.5,-20,2.2,1.24,.07,.035,.14]],
 ['rap','RAP FRONTAL','Seca, firme y presente.',1.03,0,[-4,2.2,-22,3.1,1.22,.035,.018,.09]],
 ['melodica','MELÓDICA ÍNTIMA','Cálida y con cola leve.',.98,0,[-2,1,-19,2,1.18,.12,.05,.18]],
 ['coro','CORO · CENTRO','Centro estable para coros.',.92,0,[-3,2.3,-21,2.7,1.13,.13,.055,.17]],
 ['doble-l','DOBLE · L','Refuerzo izquierdo.',.72,-.68,[-4,1.4,-23,3,1.08,.1,.035,.12]],
 ['doble-r','DOBLE · R','Refuerzo derecho.',.72,.68,[-4,1.4,-23,3,1.08,.1,.045,.15]],
 ['adlib','ADLIB · AIRE','Más ambiente y aire.',.7,.32,[-5,3,-24,2.4,1.05,.2,.1,.23]],
 ['grave','VOZ GRAVE · CERCA','Cuerpo y control.',.97,0,[-1,-.5,-18,2.6,1.16,.055,.02,.11]],
 ['brillo','BRILLO COMERCIAL','Más aire y ataque.',.98,0,[-4,3.7,-21,2.5,1.18,.085,.038,.13]],
 ['demo','DEMO RÁPIDA','Equilibrada para ideas.',1,0,[-3,1.2,-20,2.2,1.2,.075,.03,.14]]
];
const BASES=[
 ['boom','BOOM RAP MELÓDICO',86,36,'boom','Kick grave, bajo suave, piano y pad.'],
 ['piano','PIANO TRISTE',78,36,'soft','Piano protagonista y mucho aire.'],
 ['arpegio','ARPEGIO MELÓDICO',92,34,'light','Arpegio, bajo y pulso ligero.'],
 ['cine','PADS CINEMÁTICOS',76,36,'ambient','Capas largas para verso hablado.'],
 ['trap','TRAP MELÓDICO',140,36,'trap','Hat rápido, 808 y melodía mínima.'],
 ['rnb','R&B NOCTURNO',82,35,'soft','Cálido y con hueco vocal.'],
 ['boombap','BOOM BAP SUAVE',90,36,'boom','Bombo/caja clásico y armonía simple.'],
 ['minimal','MINIMAL · VOZ PRIMERO',84,36,'minimal','Muy poca base para mandar con la voz.'],
 ['coro','CORO GRANDE',96,36,'big','Más energía y capas para gancho.'],
 ['oscuro','RAP OSCURO',88,34,'dark','Grave, seco y poco brillante.']
];
const note=(pitch,at,length=.3,velocity=.6)=>({id:uid(),pitch,at,length,velocity});
function drumNotes(style){const a=[];for(let b=0;b<4;b++){const o=b*4;a.push(note(36,o,.1,.86));if(style!=='ambient'&&style!=='minimal')a.push(note(60,o+2,.1,.7));if(style==='boom'||style==='big')a.push(note(36,o+3.25,.1,.5));if(style==='trap')a.push(note(36,o+2.75,.1,.58));if(!['ambient','minimal'].includes(style))for(let h=0;h<8;h++)a.push(note(64,o+h*.5,.05,h%2?.34:.46))}return a}
function bassNotes(root){return[0,1,2,3].flatMap((b)=>[note(root-(b===2?4:b===3?2:0),b*4,2.8,.62),note(root-(b===2?4:b===3?2:0),b*4+3.2,.5,.46)])}
function harmony(root,style){const r=root+24,prog=[[0,3,7],[-2,2,5],[-4,0,3],[-2,2,5]],a=[];for(let b=0;b<4;b++){const ps=prog[b].map(x=>r+x);if(['light','trap'].includes(style)){for(let i=0;i<4;i++)a.push(note(ps[i%3]+(i===3?12:0),b*4+i,.42,.46))}else ps.forEach(p=>a.push(note(p,b*4,3.5,style==='ambient'?.35:.5)))}return a}
const midiClip=(name,notes)=>({id:uid(),type:'midi',name,start:0,length:16,notes});
function makeTrack(name,instrument,volume,notes,devices=[]){return{id:uid(),type:'instrument',name,muted:false,solo:false,armed:false,volume,pan:0,instrument,devices:devices.map(d=>({...d,id:uid()})),clips:notes.length?[midiClip(name+' · LOOP',notes)]:[]}}
function buildBase(b){const [id,name,bpm,root,style]=b,out=[];if(style!=='ambient')out.push(makeTrack('BASE · DRUMS','DRUMS',style==='minimal'?.42:.66,drumNotes(style)));out.push(makeTrack(style==='trap'?'BASE · 808':'BASE · BASS','BASS',style==='minimal'?.34:.52,bassNotes(root)));out.push(makeTrack(style==='ambient'?'BASE · PAD':'BASE · HARMONÍA',style==='ambient'?'PAD':'PIANO',style==='minimal'?.2:.42,harmony(root,style),[{type:'REVERB',enabled:true,mix:style==='ambient'?.26:.09}]));if(['boom','big','dark','ambient'].includes(style))out.push(makeTrack('BASE · PAD','PAD',style==='big'?.35:.24,harmony(root-12,'ambient'),[{type:'REVERB',enabled:true,mix:.22}]));return out}
function selectedAudio(p){const id=document.querySelector('.track-head.selected')?.closest('.track-row')?.dataset.track;return(p.tracks||[]).find(t=>String(t.id)===String(id)&&t.type==='audio')||null}
function applyVoice(v){const p=read()||{version:1,name:'Sin título',bpm:86,bars:32,meter:[4,4],metronome:false,loop:{on:false,start:0,end:16},tracks:[]};p.tracks=Array.isArray(p.tracks)?p.tracks:[];let t=selectedAudio(p);if(!t){t={id:uid(),type:'audio',clips:[],instrument:null};p.tracks.push(t)}t.name=v[1];t.muted=false;t.solo=false;t.armed=true;t.volume=v[3];t.pan=v[4];t.devices=fx(...v[5]);p.tracks.filter(x=>x.type==='audio'&&x.id!==t.id).forEach(x=>x.armed=false);save(p);location.reload()}
function applyBase(b){const p=read()||{version:1,name:'Sin título',bpm:b[2],bars:32,meter:[4,4],metronome:false,loop:{on:false,start:0,end:16},tracks:[]};p.tracks=Array.isArray(p.tracks)?p.tracks:[];p.bpm=b[2];p.bars=Math.max(32,+p.bars||32);const tag=Date.now().toString(36).slice(-3).toUpperCase();buildBase(b).forEach(t=>{t.name+=' · '+tag;p.tracks.push(t)});save(p);location.reload()}
function closeModal(){document.getElementById('ari-template-modal')?.remove()}
function openModal(kind){closeModal();const data=kind==='voice'?VOICES:BASES,m=document.createElement('div');m.id='ari-template-modal';m.className='ari-template-modal';m.innerHTML=`<div class="ari-template-dialog"><header><div><strong>${kind==='voice'?'PLANTILLAS DE VOZ':'PLANTILLAS DE BASE'}</strong><small>10 PRESETS · clic para aplicar</small></div><button type="button">×</button></header><section>${data.map((x,i)=>`<button class="ari-template-card" data-id="${x[0]}"><b>${String(i+1).padStart(2,'0')} · ${x[1]}</b><span>${kind==='voice'?x[2]:x[5]}</span>${kind==='base'?`<em>${x[2]} BPM</em>`:''}</button>`).join('')}</section></div>`;document.body.appendChild(m);m.querySelector('header button').onclick=closeModal;m.onclick=e=>{if(e.target===m)closeModal()};m.querySelectorAll('[data-id]').forEach(btn=>btn.onclick=()=>{const x=data.find(v=>v[0]===btn.dataset.id);kind==='voice'?applyVoice(x):applyBase(x)})}
function setCollapsed(on){document.documentElement.classList.toggle('ari-browser-collapsed',on);localStorage.setItem(MK,on?'1':'0');const b=document.getElementById('ari-browser-toggle');if(b){b.textContent=on?'☰ MENÚ':'⇤ MENÚ';b.setAttribute('aria-expanded',String(!on))}}
function mount(){if(document.getElementById('ari-template-style'))return;const browser=document.querySelector('.browser'),left=document.querySelector('.transport-left');if(!browser||!left){setTimeout(mount,150);return}const s=document.createElement('style');s.id='ari-template-style';s.textContent=`
.workspace{transition:grid-template-columns .2s ease!important}.browser{transition:opacity .16s ease,transform .2s ease,padding .2s ease!important;min-width:0}html.ari-browser-collapsed .workspace{grid-template-columns:0 minmax(0,1fr)!important}html.ari-browser-collapsed .browser{opacity:0;transform:translateX(-100%);padding-left:0!important;padding-right:0!important;border-right-color:transparent!important;overflow:hidden!important;pointer-events:none}#ari-browser-toggle{min-width:64px}.ari-template-launch{width:100%;height:34px;border:1px solid var(--line);background:var(--panel);border-radius:6px;text-align:left;padding:0 8px;font-size:9px;font-weight:850;margin-bottom:5px;display:flex;align-items:center;justify-content:space-between}.ari-template-launch b{color:var(--accent);font-size:8px}.ari-template-launch:hover{border-color:var(--accent);background:var(--accent-soft)}
.ari-template-modal{position:fixed;inset:0;z-index:120;background:rgba(0,0,0,.42);display:grid;place-items:center;padding:18px}.ari-template-dialog{width:min(820px,96vw);max-height:88vh;overflow:hidden;border:1px solid var(--line);background:var(--chrome);border-radius:12px;display:grid;grid-template-rows:54px minmax(0,1fr);box-shadow:0 24px 80px rgba(0,0,0,.34)}.ari-template-dialog header{display:flex;align-items:center;justify-content:space-between;padding:0 12px 0 14px;border-bottom:1px solid var(--line)}.ari-template-dialog header strong{display:block;font-size:11px}.ari-template-dialog header small{display:block;font-size:7px;color:var(--muted);margin-top:2px}.ari-template-dialog header button{width:32px;height:32px;border:1px solid var(--line);background:var(--panel);border-radius:7px;font-size:18px}.ari-template-dialog section{padding:10px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;overflow:auto}.ari-template-card{position:relative;min-height:68px;border:1px solid var(--line);background:var(--panel);border-radius:8px;padding:10px 64px 10px 11px;text-align:left}.ari-template-card:hover{border-color:var(--accent);background:var(--accent-soft)}.ari-template-card b{display:block;font-size:9px}.ari-template-card span{display:block;font-size:8px;color:var(--muted);margin-top:5px;line-height:1.35}.ari-template-card em{position:absolute;right:10px;top:10px;font-size:8px;font-style:normal;color:var(--accent);font-weight:900}
@media(max-width:820px){html:not(.ari-browser-collapsed) .workspace{grid-template-columns:188px minmax(0,1fr)!important}.browser h3,.browser-btn span{display:block!important}.browser-btn{padding:0 9px!important;justify-content:flex-start!important}.add-track{font-size:10px!important}.add-track:after{content:none!important}.ari-template-dialog section{grid-template-columns:1fr}}@media(max-width:560px){#ari-browser-toggle{min-width:58px;padding:0 6px}.ari-template-modal{padding:8px}.ari-template-dialog{width:100%;max-height:94vh}}
`;document.head.appendChild(s);const toggle=document.createElement('button');toggle.id='ari-browser-toggle';toggle.className='smallbtn';toggle.type='button';toggle.onclick=()=>setCollapsed(!document.documentElement.classList.contains('ari-browser-collapsed'));left.insertBefore(toggle,left.firstChild);const h=document.createElement('h3');h.textContent='Plantillas',v=document.createElement('button'),b=document.createElement('button');v.className=b.className='ari-template-launch';v.type=b.type='button';v.innerHTML='<span>🎙 VOZ + MEZCLA</span><b>10</b>';b.innerHTML='<span>♬ BASES</span><b>10</b>';v.onclick=()=>openModal('voice');b.onclick=()=>openModal('base');browser.insertBefore(h,browser.children[1]||null);browser.insertBefore(v,h.nextSibling);browser.insertBefore(b,v.nextSibling);setCollapsed(localStorage.getItem(MK)==='1')}
window.ARI_MUSIC_TEMPLATES={voices:VOICES,bases:BASES,open:openModal,toggle:()=>document.getElementById('ari-browser-toggle')?.click()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
